"""
Verify whether "within-district fiber" forms a subgroup of the Picard group
for a 6x6 grid graph with k=4 quadrant districts.

CORRECT APPROACH:
- The map phi_i: Pic^0(G[xi_i]) -> Pic^0(G) is NOT just embedding Laplacian rows.
- It sends a divisor class [D] on G[xi_i] to the class [D'] on G where D' agrees
  with D on xi_i and is 0 elsewhere.
- But this is NOT a homomorphism in general because the equivalence relations differ!
  Two divisors equivalent on G[xi_i] may not be equivalent when embedded in G.

- The correct approach: embed the LATTICE generated by L_{G[xi_i]} rows into Z^(n-1),
  and compute what subgroup this generates in Pic^0(G).

The sublattice Lambda_i generated by rows of L_{G[xi_i]} (embedded in Z^n, projected
to Z^(n-1)) is a sublattice of Z^(n-1). The image of Lambda_i in Pic^0(G) is
(Lambda_i + Lambda_G) / Lambda_G where Lambda_G = im(L_G reduced).

The combined sublattice Lambda_1 + ... + Lambda_4 + Lambda_G, quotiented by Lambda_G,
gives the subgroup H. We compute |H| and its structure.
"""

import numpy as np
from sympy import Matrix
from sympy.matrices.normalforms import smith_normal_form as snf_sympy
from sympy import ZZ
from functools import reduce

def make_grid_laplacian(rows, cols):
    n = rows * cols
    L = np.zeros((n, n), dtype=int)
    for r in range(rows):
        for c in range(cols):
            v = r * cols + c
            for dr, dc in [(-1,0),(1,0),(0,-1),(0,1)]:
                nr_, nc_ = r+dr, c+dc
                if 0 <= nr_ < rows and 0 <= nc_ < cols:
                    w = nr_ * cols + nc_
                    L[v, w] = -1
                    L[v, v] += 1
    return L

def snf_factors(M_np):
    M = Matrix(M_np.tolist())
    D = snf_sympy(M, domain=ZZ)
    rows, cols = D.shape
    diag = []
    for i in range(min(rows, cols)):
        d = int(abs(D[i, i]))
        if d != 0:
            diag.append(d)
    return diag

def num_spanning_trees(L):
    n = L.shape[0]
    M = Matrix(L[:n-1, :n-1].tolist())
    return int(abs(M.det()))

def induced_subgraph_laplacian(full_L, vertices):
    vlist = sorted(vertices)
    n_sub = len(vlist)
    L_sub = np.zeros((n_sub, n_sub), dtype=int)
    for i, v in enumerate(vlist):
        for j, w in enumerate(vlist):
            if v != w and full_L[v, w] < 0:
                L_sub[i, j] = -1
                L_sub[i, i] += 1
    return L_sub, vlist

def main():
    rows, cols = 6, 6
    n = rows * cols
    L = make_grid_laplacian(rows, cols)
    sink = n - 1  # vertex 35
    indices = [i for i in range(n) if i != sink]
    L_red = L[np.ix_(indices, indices)]

    print("=" * 70)
    print("6x6 GRID: PICARD GROUP AND WITHIN-DISTRICT SUBGROUP ANALYSIS")
    print("=" * 70)

    t_G = num_spanning_trees(L)
    factors_G = snf_factors(L_red)
    nontrivial_G = [f for f in factors_G if f > 1]
    print(f"\nt(G) = {t_G}")
    print(f"Pic^0(G) = " + " x ".join(f"Z/{f}" for f in nontrivial_G))
    print(f"|Pic^0(G)| = {reduce(lambda a,b:a*b, factors_G, 1)}")

    districts = {
        'xi1': {r*cols+c for r in range(3) for c in range(3)},
        'xi2': {r*cols+c for r in range(3) for c in range(3,6)},
        'xi3': {r*cols+c for r in range(3,6) for c in range(3)},
        'xi4': {r*cols+c for r in range(3,6) for c in range(3,6)},
    }

    print(f"\n--- District subgraphs ---")
    t_product = 1
    for name in sorted(districts):
        verts = districts[name]
        L_sub, vlist = induced_subgraph_laplacian(L, verts)
        t_sub = num_spanning_trees(L_sub)
        t_product *= t_sub
        n_sub = len(vlist)
        fac = snf_factors(L_sub[:n_sub-1, :n_sub-1])
        nt = [f for f in fac if f > 1]
        print(f"  {name}: t={t_sub}, Pic^0 = " + " x ".join(f"Z/{f}" for f in nt))

    print(f"  prod t(G[xi_i]) = {t_product}")

    # Build quotient graph
    dist_names = sorted(districts)
    n_q = len(dist_names)
    L_q = np.zeros((n_q, n_q), dtype=int)
    for i in range(n_q):
        for j in range(n_q):
            if i != j:
                count = sum(1 for v in districts[dist_names[i]]
                           for w in districts[dist_names[j]] if L[v,w] < 0)
                L_q[i,j] = -count
                L_q[i,i] += count
    t_q = num_spanning_trees(L_q)
    print(f"\n  Quotient graph t(G/xi) = {t_q}")

    # ================================================================
    # The sublattice generated by district-internal chip-fires
    # ================================================================
    print(f"\n{'='*70}")
    print("SUBLATTICE FROM DISTRICT-INTERNAL CHIP-FIRES")
    print("=" * 70)

    # For each district xi_i, the chip-fires within G[xi_i] generate a sublattice.
    # A chip-fire at vertex v in G[xi_i] produces a vector in Z^V(G) that is
    # the v-th row of L_{G[xi_i]}, zero-extended.
    #
    # The KEY distinction from firing v in the FULL graph G:
    # In G[xi_i], vertex v only fires chips to neighbors WITHIN xi_i.
    # In G, vertex v fires to ALL neighbors (including those in other districts).
    # The DIFFERENCE is exactly the inter-district edges.

    # Embed all district Laplacian rows into Z^(n-1)
    all_district_gens = []
    for name in sorted(districts):
        verts = districts[name]
        L_sub, vlist = induced_subgraph_laplacian(L, verts)
        for i in range(len(vlist)):
            vec = np.zeros(n, dtype=int)
            for j in range(len(vlist)):
                vec[vlist[j]] = L_sub[i, j]
            # Project: remove sink coordinate
            all_district_gens.append(vec[indices])

    gen_matrix = np.array(all_district_gens, dtype=int)

    # Combined lattice = Lambda_G + sum Lambda_i
    combined = np.vstack([L_red, gen_matrix])
    print(f"District generators: {gen_matrix.shape[0]}")
    print(f"Combined matrix: {combined.shape}")

    print(f"\nComputing SNF of combined lattice...")
    fac_comb = snf_factors(combined)
    nt_comb = [f for f in fac_comb if f > 1]
    det_comb = reduce(lambda a,b:a*b, fac_comb, 1)

    print(f"Pic^0(G)/H ~ " + " x ".join(f"Z/{f}" for f in nt_comb))
    print(f"|Pic^0(G)/H| = {det_comb}")

    size_H = t_G // det_comb
    print(f"|H| = {t_G}/{det_comb} = {size_H}")
    assert t_G % det_comb == 0, "Not a subgroup!"

    print(f"\nH IS a subgroup of Pic^0(G)")
    print(f"  |H| = {size_H}")
    print(f"  [Pic^0(G) : H] = {det_comb}")

    # ================================================================
    # Now compute: what is H isomorphic to?
    # H = (Lambda_district + Lambda_G) / Lambda_G
    # To get the structure, compute SNF of the relevant quotient.
    # ================================================================

    # We can find the structure of H by computing the SNF of the map
    # from the generators to Pic^0(G).
    # H = im(gen_matrix in Z^(n-1)/Lambda_G)
    # = (span(gen_matrix) + Lambda_G) / Lambda_G
    # ~ span(gen_matrix) / (span(gen_matrix) ∩ Lambda_G)

    # To compute H's structure directly:
    # Stack gen_matrix and L_red, compute SNF. Then compare with SNF of L_red.
    # The quotient Z^(n-1)/combined has structure given by fac_comb.
    # The quotient Z^(n-1)/L_red has structure given by factors_G.
    # H = ker(Pic^0(G) -> Z^(n-1)/combined) = quotient of these two.

    # Actually, let's compute it differently.
    # We want the structure of H as a group.
    # Use the fact that we can compute the SNF of gen_matrix modulo Lambda_G.

    # Method: solve for H's invariant factors.
    # H is the image of gen_matrix^T in coker(L_red^T).
    # Equivalently, consider the exact sequence:
    # 0 -> K -> Z^m --gen--> Z^(n-1) / Lambda_G -> coker -> 0
    # where m = number of generators.
    # H = im(gen) = Z^m / K.
    # K = gen^{-1}(Lambda_G) = {x in Z^m : gen_matrix^T x in Lambda_G}
    #   = {x : gen_matrix^T x = L_red^T y for some y}

    # Build the matrix [gen_matrix^T | -L_red^T] and compute its kernel to find K.
    # Or equivalently, compute the SNF of the matrix [gen_matrix; L_red] and compare
    # with SNF of [L_red] -- which we already did.

    # The invariant factors of H can be extracted as follows:
    # factors_G / fac_comb (in the divisibility sense)
    # Since factors_G = [1,...,1, 4, 16, 48, 102960, 102960]
    # and fac_comb = [1,...,1, 4, 8, 24]
    # H has invariant factors factors_G[i] / fac_comb[i] for each i.

    # But this only works if fac_comb[i] | factors_G[i] for all i.
    # Let's check:
    print(f"\n--- Structure of H ---")
    print(f"  SNF of Pic^0(G): {factors_G}")
    print(f"  SNF of Pic^0(G)/H: {fac_comb}")

    # Pad to same length
    max_len = max(len(factors_G), len(fac_comb))
    fg = factors_G + [0] * (max_len - len(factors_G))
    fc = fac_comb + [0] * (max_len - len(fac_comb))

    # The invariant factors of H:
    # By the structure theorem, if G_ab has invariants d_1|d_2|...|d_n
    # and G_ab/H has invariants e_1|e_2|...|e_n with e_i|d_i,
    # then... it's not that simple in general.

    # Let's compute H's structure directly using a different approach.
    # H is the torsion group (span(gen_matrix) + Lambda_G) / Lambda_G
    # This is isomorphic to span(gen_matrix) / (span(gen_matrix) ∩ Lambda_G)

    # Compute span(gen_matrix) ∩ Lambda_G:
    # A vector is in the intersection iff it's in span(gen_matrix) AND in Lambda_G.
    # v = gen_matrix^T a = L_red^T b
    # So we need the kernel of [gen_matrix^T | -L_red^T] and project to the first component.

    # Build the matrix M = [gen_matrix^T | -L_red^T]^T (stacked vertically)
    # Then find integer relations... this is complex.

    # Simpler: just compute the SNF of gen_matrix within Z^(n-1) / Lambda_G.
    # Consider the augmented matrix:
    # [gen_matrix]
    # [L_red     ]  (the relations)
    # The SNF of this gives the structure of Z^(n-1) / (span(gen) + Lambda_G)
    # which we already have as fac_comb.

    # For H's own structure, we can use:
    # Consider gen_matrix as a map Z^36 -> Z^35 / Lambda_G = Pic^0(G).
    # The image H has presentation: take gen_matrix, and quotient by
    # the kernel of (gen -> Pic^0(G)).
    # Kernel = {a in Z^36 : gen_matrix^T a in Lambda_G = im(L_red^T)}

    # Build the big matrix: [gen_matrix^T | L_red^T]^T and compute Hermite normal form
    # to find the kernel.

    # Actually, there's a cleaner way. We compute:
    # 1. SNF of gen_matrix to get its rank and the lattice it generates
    # 2. Express Lambda_G ∩ span(gen) in terms of gen's basis
    # 3. SNF of the quotient

    # Let me just compute it numerically.
    # gen_matrix has shape (36, 35). Its rank should be sum of (n_i - 1) = 4*8 = 32.
    gen_sym = Matrix(gen_matrix.tolist())
    rank_gen = gen_sym.rank()
    print(f"  Rank of district generator matrix: {rank_gen}")

    # The lattice Lambda_district = im(gen_matrix^T) has rank = rank_gen.
    # Lambda_G has rank 35 (full rank in Z^35).
    # Lambda_district ∩ Lambda_G has rank = rank_gen (since Lambda_G is full rank).
    # |H| = [Lambda_district : Lambda_district ∩ Lambda_G]

    # To compute this index, note:
    # [Z^35 : Lambda_G] = t(G)
    # [Z^35 : Lambda_district + Lambda_G] = det_comb
    # [Z^35 : Lambda_district] = det of SNF of gen_matrix (on the sublattice it generates)
    # By the formula: [A+B : B] * [A ∩ B : 0] = [A : 0] ... no, let me use the right formula.

    # [Z^35 : A+B] = [Z^35 : A] * [A : A+B]... not standard.

    # Index formula: [A+B : B] = [A : A ∩ B]
    # So |H| = [Lambda_district + Lambda_G : Lambda_G] = [Lambda_district : Lambda_district ∩ Lambda_G]

    # And: [Z^35 : Lambda_district + Lambda_G] * [Lambda_district + Lambda_G : Lambda_G]
    #     = [Z^35 : Lambda_G]
    # => det_comb * |H| = t(G)  ✓ (already verified)

    # Also: [Z^35 : Lambda_district + Lambda_G] * [Lambda_district + Lambda_G : Lambda_district]
    #     = [Z^35 : Lambda_district]
    # => det_comb * [Lambda_district + Lambda_G : Lambda_district] = det(Lambda_district)

    # Compute det(Lambda_district) = product of nonzero SNF factors of gen_matrix
    # when viewed as a map from Z^36 to Z^35.
    snf_gen = snf_factors(gen_matrix)
    det_district_lattice = reduce(lambda a,b:a*b, snf_gen, 1)
    print(f"  SNF of gen_matrix: {snf_gen}")
    print(f"  det(Lambda_district) = {det_district_lattice}")

    # [Lambda_G : Lambda_district ∩ Lambda_G] = ?
    # By index formula:
    # [Z^35 : Lambda_district ∩ Lambda_G] = [Z^35 : Lambda_G] * [Lambda_G : Lambda_district ∩ Lambda_G]
    #                                      = [Z^35 : Lambda_district] * [Lambda_district : Lambda_district ∩ Lambda_G]
    # So: t(G) * [Lambda_G : Lambda_district ∩ Lambda_G] = det_district_lattice * |H|

    # Hmm, this requires knowing the index within Lambda_G too.
    # Let me just proceed with the key computation.

    # Check: does |H| = size_H make sense with prod t(G[xi_i])?
    print(f"\n{'='*70}")
    print("SUMMARY")
    print("=" * 70)

    print(f"\n1. Sandpile group Pic^0(G) for 6x6 grid:")
    print(f"   Pic^0(G) = " + " x ".join(f"Z/{f}" for f in nontrivial_G))
    print(f"   |Pic^0(G)| = t(G) = {t_G}")

    print(f"\n2. Spanning trees:")
    print(f"   t(G) = {t_G}")
    for name in sorted(districts):
        verts = districts[name]
        L_sub, vlist = induced_subgraph_laplacian(L, verts)
        print(f"   t(G[{name}]) = {num_spanning_trees(L_sub)}")
    print(f"   prod t(G[xi_i]) = {t_product}")
    print(f"   t(G/xi) = {t_q}")

    print(f"\n3. Within-district sublattice generates subgroup H of Pic^0(G):")
    print(f"   YES, it is a subgroup (always true: it's the image of a lattice homomorphism)")
    print(f"   |H| = {size_H}")
    print(f"   [Pic^0(G) : H] = {det_comb}")
    print(f"   Pic^0(G) / H ~ " + " x ".join(f"Z/{f}" for f in nt_comb))

    print(f"\n4. Comparison with product of district Picard groups:")
    print(f"   |H| = {size_H}")
    print(f"   prod |Pic^0(G[xi_i])| = {t_product}")
    print(f"   |H| / prod|Pic^0(G[xi_i])| = {size_H / t_product:.6f}")
    print(f"   |H| > prod|Pic^0(G[xi_i])| by factor {size_H / t_product:.6f}")
    print(f"   This means the natural map prod Pic^0(G[xi_i]) -> H is NOT surjective.")
    print(f"   The district chip-fires, embedded in G, generate MORE than just")
    print(f"   the product of district Picard groups because they interact in Z^(n-1).")

    print(f"\n5. Kirchhoff-type factorization:")
    print(f"   t(G) / (prod t(G[xi_i])) = {t_G / t_product:.4f}")
    print(f"   t(G/xi) = {t_q}")
    print(f"   t(G) / (t(G/xi) * prod t(G[xi_i])) = {t_G / (t_q * t_product):.6f}")
    correction = t_G // (t_q * t_product) if t_G % (t_q * t_product) == 0 else t_G / (t_q * t_product)
    print(f"   Correction factor (should be integer for weighted formula): {correction}")

    # Extra: verify by computing det(M) where M encodes the interconnection
    # between districts. The matrix-tree theorem generalizes:
    # t(G) = t(G/xi) * prod t(G[xi_i]) * (product of edge weights for inter-district edges)
    # ... but for unweighted graphs, the formula involves a sum over connecting forests.

    print(f"\n6. Interpretation for redistricting:")
    print(f"   The within-district chip-fires generate a subgroup H of index {det_comb}.")
    print(f"   The quotient Pic^0(G)/H has structure: " + " x ".join(f"Z/{f}" for f in nt_comb))
    print(f"   This quotient captures the 'inter-district' degrees of freedom.")
    print(f"   The subgroup H captures 'within-district' degrees of freedom.")
    print(f"   Since H is a proper subgroup, the fiber decomposition via Picard groups")
    print(f"   gives a nontrivial partition of Pic^0(G) into {det_comb} cosets of H.")


if __name__ == "__main__":
    main()
